In [1]:
import pandas as pd
#训练数据初步统计
train_data_path = r"C:\Users\ccs\Documents\dataWhale\used_car_train_20200313\used_car_train_20200313.csv"
train_data_df =  pd.read_csv(train_data_path, sep=' ')
# print("原数据的数量:\n",train_data_df.count())
# print("去重后的数量:\n",train_data_df.drop_duplicates().count())
train_data_df.describe(include='all')

,SaleID,name,regDate,model,brand,bodyType,fuelType,gearbox,power,kilometer,...,v_5,v_6,v_7,v_8,v_9,v_10,v_11,v_12,v_13,v_14
count,150000.000000,150000.000000,1.500000e+05,149999.000000,150000.000000,145494.000000,141320.000000,144019.000000,150000.000000,150000.000000,...,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,74999.500000,68349.172873,2.003417e+07,47.129021,8.052733,1.792369,0.375842,0.224943,119.316547,12.597160,...,0.248204,0.044923,0.124692,0.058144,0.061996,-0.001000,0.009035,0.004813,0.000313,-0.000688
std,43301.414527,61103.875095,5.364988e+04,49.536040,7.864956,1.760640,0.548677,0.417546,177.168419,3.919576,...,0.045804,0.051743,0.201410,0.029186,0.035692,3.772386,3.286071,2.517478,1.288988,1.038685
min,0.000000,0.000000,1.991000e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,...,0.000000,0.000000,0.000000,0.000000,0.000000,-9.168192,-5.558207,-9.639552,-4.153899,-6.546556
25%,37499.750000,11156.000000,1.999091e+07,10.000000,1.000000,0.000000,0.000000,0.000000,75.000000,12.500000,...,0.243615,0.000038,0.062474,0.035334,0.033930,-3.722303,-1.951543,-1.871846,-1.057789,-0.437034
50%,74999.500000,51638.000000,2.003091e+07,30.000000,6.000000,1.000000,0.000000,0.000000,110.000000,15.000000,...,0.257798,0.000812,0.095866,0.057014,0.058484,1.624076,-0.358053,-0.130753,-0.036245,0.141246
75%,112499.250000,118841.250000,2.007111e+07,66.000000,13.000000,3.000000,1.000000,0.000000,150.000000,15.000000,...,0.265297,0.102009,0.125243,0.079382,0.087491,2.844357,1.255022,1.776933,0.942813,0.680378
max,149999.000000,196812.000000,2.015121e+07,247.000000,39.000000,7.000000,6.000000,1.000000,19312.000000,15.000000,...,0.291838,0.151420,1.404936,0.160791,0.222787,12.357011,18.819042,13.847792,11.147669,8.658418

In [ ]:
#空值统计
train_data_df.isnull().sum()

In [15]:
#对于字符型指标---分组统计
%matplotlib inline
category_columns  = ['model', 'brand', 'bodyType', 'fuelType','gearbox','notRepairedDamage','regionCode','seller', 'offerType']
# print(train_data_df['model'])
for i in category_columns:
    print(train_data_df.groupby(i).size())

model
0.0      11762
1.0       6038
2.0        286
3.0        920
4.0       8445
5.0       2063
6.0        301
7.0       1460
8.0       4391
9.0         55
10.0      2004
11.0      1775
12.0       237
13.0      3762
14.0       351
15.0       518
16.0      1349
17.0      3121
18.0        42
19.0      9573
20.0       395
21.0      1872
22.0      1524
23.0      1696
24.0       412
25.0       205
26.0      4496
27.0       260
28.0       102
29.0      5186
         ...
218.0       57
219.0      112
220.0       16
221.0       95
222.0       88
223.0       13
224.0       18
225.0       65
226.0       26
227.0       17
228.0      125
229.0       10
230.0       16
231.0       23
232.0       10
233.0       20
234.0       23
235.0        7
236.0       11
237.0       17
238.0       44
239.0       14
240.0        2
241.0       10
242.0        2
243.0        4
244.0        3
245.0        2
246.0        7
247.0        1
Length: 248, dtype: int64
brand
0     31480
1     13794
2       321
3      2461
4     16737
5      4665
6     10217
7      2361
8      2077
9      7306
10    14249
11     2945
12     1109
13     3817
14    16089
15     1458
16     2223
17      913
18      316
19     1388
20     1236
21     1547
22     1085
23      186
24      772
25     2064
26      966
27     2053
28      649
29      406
30      940
31      318
32      592
33      218
34      227
35      180
36      228
37      333
38       65
39        9
dtype: int64
bodyType
0.0    41420
1.0    35272
2.0    30324
3.0    13491
4.0     9609
5.0     7607
6.0     6482
7.0     1289
dtype: int64
fuelType
0.0    91656
1.0    46991
2.0     2212
3.0      262
4.0      118
5.0       45
6.0       36
dtype: int64
gearbox
0.0    111623
1.0     32396
dtype: int64
notRepairedDamage
-       24324
0.0    111361
1.0     14315
dtype: int64
regionCode
0        63
1        17
2        26
3        30
4        65
5        39
6        40
7         7
8        25
9         7
10       45
11       35
12       43
13       31
14       28
15       12
16       62
17       51
18       47
19       11
20       19
21       30
22       35
23       60
24      130
25        8
26       57
27       15
28       34
29       42
       ...
8069      1
8070      1
8071      1
8072      1
8073      2
8077      1
8078      2
8081      1
8082      1
8084      1
8086      1
8087      1
8088      2
8090      1
8092      1
8093      1
8094      1
8097      1
8100      1
8102      1
8103      2
8104      1
8105      1
8106      1
8107      1
8109      1
8112      1
8113      1
8117      1
8120      1
Length: 7905, dtype: int64
seller
0    149999
1         1
dtype: int64
offerType
0    150000
dtype: int64

In [25]:
#对于连续型指标---正态分布检验
from scipy.stats import stats
numerical_columns  = ['regDate','power', 'kilometer','creatDate', 'price', 'v_0', 'v_1', 'v_2', 'v_3',
           'v_4', 'v_5', 'v_6', 'v_7', 'v_8', 'v_9', 'v_10', 'v_11', 'v_12',
           'v_13', 'v_14']
# print(scipy.stats.shapiro(train_data_df['regDate']))
# k2, p = stats.normaltest(x)
print('看P-Value是否满足正态分布，小于0.001即满足',list(map(lambda x:scipy.stats.normaltest(train_data_df[x])[1],numerical_columns)))

看P-Value是否满足正态分布，小于0.001即可 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [26]:
#连续型指标的均值、方差、标准差，四分位数，最大最小值观察
train_data_df[numerical_columns].describe(include='all')

,regDate,power,kilometer,creatDate,price,v_0,v_1,v_2,v_3,v_4,v_5,v_6,v_7,v_8,v_9,v_10,v_11,v_12,v_13,v_14
count,1.500000e+05,150000.000000,150000.000000,1.500000e+05,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,2.003417e+07,119.316547,12.597160,2.016033e+07,5923.327333,44.406268,-0.044809,0.080765,0.078833,0.017875,0.248204,0.044923,0.124692,0.058144,0.061996,-0.001000,0.009035,0.004813,0.000313,-0.000688
std,5.364988e+04,177.168419,3.919576,1.067328e+02,7501.998477,2.457548,3.641893,2.929618,2.026514,1.193661,0.045804,0.051743,0.201410,0.029186,0.035692,3.772386,3.286071,2.517478,1.288988,1.038685
min,1.991000e+07,0.000000,0.500000,2.015062e+07,11.000000,30.451976,-4.295589,-4.470671,-7.275037,-4.364565,0.000000,0.000000,0.000000,0.000000,0.000000,-9.168192,-5.558207,-9.639552,-4.153899,-6.546556
25%,1.999091e+07,75.000000,12.500000,2.016031e+07,1300.000000,43.135799,-3.192349,-0.970671,-1.462580,-0.921191,0.243615,0.000038,0.062474,0.035334,0.033930,-3.722303,-1.951543,-1.871846,-1.057789,-0.437034
50%,2.003091e+07,110.000000,15.000000,2.016032e+07,3250.000000,44.610266,-3.052671,-0.382947,0.099722,-0.075910,0.257798,0.000812,0.095866,0.057014,0.058484,1.624076,-0.358053,-0.130753,-0.036245,0.141246
75%,2.007111e+07,150.000000,15.000000,2.016033e+07,7700.000000,46.004721,4.000670,0.241335,1.565838,0.868758,0.265297,0.102009,0.125243,0.079382,0.087491,2.844357,1.255022,1.776933,0.942813,0.680378
max,2.015121e+07,19312.000000,15.000000,2.016041e+07,99999.000000,52.304178,7.320308,19.035496,9.854702,6.829352,0.291838,0.151420,1.404936,0.160791,0.222787,12.357011,18.819042,13.847792,11.147669,8.658418

In [29]:
#连续型指标异常值检测--超过80%的指标检验异常则判定为该样本异常，需过滤
import numpy as np
from collections import Counter


# Outlier detection
def detect_outliers(df, n, features):
    """
    Takes a dataframe df of features and returns a list of the indices
    corresponding to the observations containing more than n outliers according
    to the Tukey method.
    """
    outlier_indices = []

    # iterate over features(columns)
    for col in features:
        # 1st quartile (25%)
        Q1 = np.percentile(df[col], 25)
        # 3rd quartile (75%)
        Q3 = np.percentile(df[col], 75)
        # quartile spacing (IQR)
        IQR = Q3 - Q1
        # outlier step
        outlier_step = 1.5 * IQR

        # Determine a list of indices of outliers for feature col
        outlier_list_col = df[(df[col] < Q1 - outlier_step) | (df[col] > Q3 + outlier_step)].index

        # append the found outlier indices for col to the list of outlier indices
        outlier_indices.extend(outlier_list_col)

    # select observations containing more than n outliers
    outlier_indices = Counter(outlier_indices)
    multiple_outliers = list(k for k, v in outlier_indices.items() if v > n)

    return multiple_outliers

detect_outliers(train_data_df,int(len(numerical_columns)*0.8),numerical_columns)

[]

In [ ]:
#绘制各变量的散点图
%matplotlib inline
import seaborn as sns
sns.pairplot(train_data_df['v_0', 'v_1', 'v_2', 'v_3',
           'v_4', 'v_5', 'v_6', 'v_7', 'v_8', 'v_9', 'v_10', 'v_11', 'v_12',
           'v_13', 'v_14'])
plt.show()

In [7]:
#自变量之间是否存在多重共线性关系检验
# 结果显示，若VIF低于10，说明自变量之间并不存在多重共线性的隐患，否则，存在
import patsy.highlevel
import statsmodels.api as sm
import statsmodels.compat.scipy
import statsmodels.stats.outliers_influence
col_list = list(train_data_df.columns)
col_list.remove('price')
y, X = patsy.highlevel.dmatrices('price~{columns}'.format(columns=('+').join(col_list)), data=train_data_df,
                                     return_type='dataframe')
vif = pd.DataFrame()
vif["VIF Factor"] = ['{:.5f}'.format(statsmodels.stats.outliers_influence.variance_inflation_factor(X.values, i)) for i in
                         range(X.shape[1])]
vif["features"] = X.columns
print(vif)

                VIF Factor                  features
0                  0.00000                 Intercept
1                  1.70709  notRepairedDamage[T.0.0]
2                  1.59688  notRepairedDamage[T.1.0]
3                  1.00018                    SaleID
4                  1.73883                      name
5                  7.60364                   regDate
6                  1.97338                     model
7                  1.35061                     brand
8                  1.68997                  bodyType
9                  1.28142                  fuelType
10                 1.22395                   gearbox
11                 1.08050                     power
12                 1.61190                 kilometer
13                 1.13977                regionCode
14                 1.00093                    seller
15                     nan                 offerType
16                 1.00036                 creatDate
17    32516964818559.53906                       v_0
18                     inf                       v_1
19   500399958596721.75000                       v_2
20     8521475170048.24219                       v_3
21         456754595.58848                       v_4
22           4996906.56870                       v_5
23            409914.66895                       v_6
24           1435387.53140                       v_7
25           1520943.27338                       v_8
26           2007071.97161                       v_9
27                     inf                      v_10
28  9007199254740992.00000                      v_11
29   474063118670578.50000                      v_12
30        2946764831.56047                      v_13
31            263684.87479                      v_14